### ISSUE TITLE
Feature Request: Require fidelity in as_numeric conversion

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/PKPDmisc#43]
I often find myself wanting a conversion from character to numeric where I **know** that the output was only the conversion that I wanted.  Specifically, I want to know that no `NA` values were introduced.

I think that a new option to `as_numeric()` could cover this, an argument named something like `require_conversion` with values of `FALSE` (current behavior), or `TRUE` (confirm that `all(is.na(input) == is.na(output))` is TRUE).

Would a PR for that be of interest?  If so, do you have a different argument name that you prefer?

**Comment by dpastoor** [comment]
sounds great - one thing to mull on api-wise is there is another function `unique_non_numerics` that will actually give you back the unique values that _were_ coerced, if any. 

The next question is what you want to do if the all() fails - should it stop() and what might the error message say.

This is good timing for a PR - i'm going to try to do some clean up to get a new release up on CRAN with some other misc cleanup

**Comment by billdenney** [comment]
I debated having three levels to `require_conversion` when I was writing the above:

* `NULL` current behavior
* `FALSE` warning
* `TRUE` stop

And, I would suggest for the warning and stop messages, use the output of `unique_non_numerics()` to let the user know what the problems were.  (And, in parallel, I would suggest sorting the output of `unique_non_numerics()` to make it easier to read that list.  I would probably do that in the `unique_non_numerics()` function.)

The two differences between `as.numeric()` and `as_numeric()` with `require_conversion=FALSE` would be capturing factors and giving information on what actual values were problems.

Thoughts?

**Comment by dpastoor** [comment]
sounds good to me
