### ISSUE TITLE
unable to install PKPDmisc pakages

### ISSUE THREAD

**Issue by AprilCCC** [metrumresearchgroup/PKPDmisc#47]
Hi ,
Did anyone come across install issue? Using R 4.1.3 in Mac ,tried to install PKPDmisc package, but it shows warning:
package "PKPDmisc" is not available for this version of R
How to solve this?

Thanks

**Comment by kyleam** [comment]
Thanks for reporting the issue. Unfortunately the install instructions in the README are stale.  PKPDmisc is no longer on CRAN.  (It looks like it was archived on [2020-06-15](https://cran.r-project.org/web/packages/PKPDmisc/).)

However, it is still available on [MPN](https://mpn.metworx.com/docs/packages/PKPDmisc).  You can install it by including the MPN in your `repos`.  For example:

```R
install.packages(
  "PKPDmisc",
  repos = c("CRAN" = "https://cran.rstudio.com",
            "MPN" = "https://mpn.metworx.com/snapshots/stable/2022-03-21"))
```

I'm not aware of any effort to get it back onto CRAN at this time.  We should update the README to drop mention of CRAN and point to MPN.

**Comment by AprilCCC** [comment]
Hi Kyle, Thanks for the update.
