### ISSUE TITLE
installament of the package

### ISSUE THREAD

**Issue by MahmoudAliAfifi** [metrumresearchgroup/PKPDmisc#50]
I can not install the package from CRAN or GITHUB, can anyone help me?

**Comment by kyleam** [comment]
As mentioned at #47, PKPDmisc is no longer on CRAN.  You don't describe how you tried to install it from GitHub and what the failure was, but that should still work.  (I just verified a successful install using the snippet from the README: `devtools::install_github("metrumresearchgroup/PKPDmisc")`.)

You can also install it from [MPN](https://mpn.metworx.com/docs/) (see #47 for an example).

Note that PKPDmisc was very recently superseded by [mrgmisc](https://github.com/metrumresearchgroup/mrgmisc).  If the functionality you're using is available there, you may want to use that instead.  (I'm not aware of any plans to put mrgmisc on CRAN, but it will be on MPN with the next snapshot.  You can also install it from GitHub.)

[ @michaelmcd18 I think it'd be a good idea to update this repo to point to mrgmisc, at least once mrgmisc is on MPN. 
 Would you mind taking care of that? ]

**Comment by kyleam** [comment]
> [ @michaelmcd18 I think it'd be a good idea to update this repo to point to mrgmisc, at least once mrgmisc is on MPN.
> Would you mind taking care of that? ]

Scratch that, I see @seth127 just did that in 78f5542 (Updating README to point to mrgmisc repo, 2022-10-17).

**Comment by kyleam** [comment]
@MahmoudAliAfifi, I'll close this given that status of this package, but, as noted above, you should be able to install PKPDmisc from GitHub or MPN.  If you post the specific installation steps you're using and the failure output, we may be able to spot what's going wrong (but, as mentioned above, any further development is likely to be restricted to mrgmisc).
